### ISSUE TITLE
Question about "Staged Compilation with Two-Level Type Theory"

### ISSUE THREAD

**Issue by andremarianiello** [AndrasKovacs/AndrasKovacs.github.io#1]
I was reading https://andraskovacs.github.io/pdfs/2ltt.pdf and I noticed that when you introduced `cons0`, it was typed as

> cons0 : (𝐴 : U0) → 𝐴 → List0 𝐴

that is, without a List0 𝐴 parameter. It is then used with a parameter ~as

> cons0 ∼𝐵 ∼(𝑓 ⟨𝑎⟩) bs) (nil0 ∼𝐵) ∼𝑎s

I would guess this was just a minor typo but I wanted to check to see if I was missing something. Also, sorry if this was the wrong place to contact you!

**Comment by AndrasKovacs** [comment]
Hi! This place is fine. Yes, it's a typo, thanks! I pushed a fixed version.
